FROM jenkins/jenkins:lts

USER root

ARG DOCKER_GID=1001

RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/*

RUN groupadd -g ${DOCKER_GID} docker || true && usermod -aG docker jenkins

# Copia el script de arranque que ajusta los permisos del socket
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Usa nuestro entrypoint
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

USER jenkins
